FROM openjdk:17-jdk-alpine

# Set the working directory in the container
#WORKDIR /app

COPY target/docker-school-0.0.1-SNAPSHOT.jar school-0.0.1-SNAPSHOT.jar

# Expose the port the application runs on
EXPOSE 8080
ENTRYPOINT ["java","-jar","/school-0.0.1-SNAPSHOT.jar"]